google.load("visualization","1",{packages:["corechart","table"]});$.cookie.json=!0;
var app={map:null,basemaps:{"Light Gray Background Map":L.tileLayer("http://{s}.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/{styleId}/256/{z}/{x}/{y}.png",{styleId:22677,attribution:"Map Provided by <a href='http://cloudmade.com/' target='_blank'>Cloudmade</a>",title:"Cloudmade"}),"OpenStreet Map":L.tileLayer("http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"Map Provided by <a href='http://www.openstreetmap.org/' target='_blank'>Open Street Map</a>",title:"Open Street Map"})},
layers:{demographicData:null,selectedZipcodeLayer:null},zipcodeFieldName:"zip_code",geocodingResult:{type:"GEOJSON",url:null,title:null,column:{statistics:""},keywords:[],showLayerNames:[]},controls:{mapGallery:L.Control.extend({options:{collapsed:!0,position:"topright",text:"Map Gallery"},initialize:function(a){L.Util.setOptions(this,a)},onAdd:function(a){a=L.DomUtil.create("div","leaflet-control-mapGallery");$(a).html("<ul><li title='Showing markers' layer='geoJsonLayer' style='background-color:#5B92C0'><img src='images/marker-icon.png' /></li><li title='Cluster Map' layer='markerClusterLayer'><img src='images/gallery-cluster.png' /></li><li title='Hotspots' layer='heatMapLayer'><img src='images/gallery-heatmap.png' /></li></ul>").find("ul li").on({click:function(){var b=
$(this),a=b.attr("layer"),d=app.geocodingResult[a];d._map?(app.map.removeLayer(d),b.css({"background-color":""})):(d.addTo(app.map),"markerClusterLayer"==a&&d.bringToFront(),b.css({"background-color":app.css.mapGalleryHighlightColor}),$("#mapPopup_"+a).show())},mouseover:function(){$(".mapPopupWidget").hide();var a=$(this).attr("layer");app.geocodingResult[a]._map&&$("#mapPopup_"+a).show()},mouseleave:function(){}});return a}}),toc:null,legend:L.Control.extend({options:{position:"bottomright",text:"Legend"},
initialize:function(a){L.Util.setOptions(this,a)},onAdd:function(a){return L.DomUtil.create("div","leaflet-control-legend")}})},popup:null,initCenterLatLng:[35,-100],initCenterZoom:4,showLayers:[],dataTable:null,demographicData:{fam_size:"average faimily size",income:"median household income",age0_9:"age 5 to 9 years",age10_19:"age 10 to 19 years",age20_64:"age 20 to 64 years",age65_abov:"age 65 years and above",pop:"population",popDen:"population density"},geojsonReader:new jsts.io.GeoJSONReader,
mapGalleryHtml:"",css:{dataTable_highlightRow:{"background-color":"#ED3D86",color:"#ffffff"},dataTable_height:function(){return $("#dataPanel").height()-70},mapGalleryHighlightColor:"#5B92C0"},$tr:null,userInfo:{email:null,city:null,country:null,valideCreditcard:!1,accountType:null,credit:null,oauth:null},oauthWindow:null,tutorial:null,introJS:null,geomask:!1,highlightMarker:new L.Marker([0,0])};pathgeo.service.demographicData({callback:function(a){app.layers.demographicData=a}});
$(document).on({ready:function(){},pageshow:function(){init_login();init_UI();init_map();readTutorial()},pageinit:function(){$("div[data-role='popup']").popup({history:!1})}});
function init_login(){if($.cookie("PathGeo")){var a=app.userInfo.email=$.cookie("PathGeo").email;app.userInfo.oauth=$.cookie("PathGeo").oauth;getAccountInfo(a);_gaq.push(["_trackEvent","Account","Login",a])}else var b=setInterval(function(){"-99999px"!=$("#dialog_login-popup").css("top")?clearInterval(b):$("#dialog_login").popup("open")},500)}
function init_map(){app.map=L.map("div_map",{center:app.initCenterLatLng,zoom:app.initCenterZoom,layers:[app.basemaps["Light Gray Background Map"]],attributionControl:!0,trackResize:!0});app.map.zoomControl.setPosition("bottomright");app.controls.toc=L.control.layers(app.basemaps).setPosition("topright");$.each(app.controls,function(a,b){"toc"==a?app.map.addControl(b):app.map.addControl(new b)});$(".leaflet-control-attribution a:first-child").attr("href","http://www.pathgeo.com").html("PathGeo");
$(".leaflet-control-attribution").append(" & Icon from <a href='http://medialoot.com/item/free-vector-map-location-pins/' target='_blank'>MediaLoot</a>");app.map.on("baselayerchange",function(a){$(".leaflet-control-attribution a:first-child").attr("href","http://www.pathgeo.com").html("PathGeo")});app.map.on({popupopen:function(a){},popupclose:function(a){},baselayerchange:function(a){(a=a.layer.options.title)&&(""!=a&&app.userInfo.email&&""!=app.userInfo.email)&&_gaq.push(["_trackEvent","BaseMap",
a,app.userInfo.email])}})}
function init_UI(){$("#content").height($(window).height()-$("#header").height());setTimeout(function(){},1E3);$(".infoPanel").css({height:$("#content").height()-20,width:0.375*$("#content").width()});$(window).resize(function(){$("#content").height($(window).height()-$("#header").height());$(".infoPanel").css({height:$("#content").height()-20,width:0.375*$("#content").width()});$(".dataTables_scrollBody").css({height:app.css.dataTable_height()})});$("#slider").nivoSlider({effect:"fade"});$(".mapPopupWidget").on({mouseover:function(){},
mouseleave:function(){$(".mapPopupWidget").hide()}});$(document).mouseup(function(a){var c=$(".dataTable_menu, #dataTable_chartControlMenu, .mapPopupWidget, #userPopupMenu");c.is(a.target)||0!==c.has(a.target).length||c.hide()});$("#businessActions_type").change(function(){showBusinessAction(this.value)});$(".infoPanel").append("<a id='closeInfoPanel' href='#' data-role='button' data-theme='a' data-icon='delete' data-iconpos='notext'  style='position:absolute; right:-10px; top:-6px;z-index:500;' onclick='closeInfoPanel()'>Close</a>");
$(".infoPanel #closeInfoPanel").buttonMarkup("refresh");$("#mapPopup_geoJsonLayer .mapPopupWidget_content ul li").click(function(){var a=$(this).find("img"),c=a.attr("src"),d=a.attr("markerWidth"),a=a.attr("markerHeight");changeMarkerIcon(c,d,a)});$("#userMenu_button ul li").click(function(){var a=$(this),c=a.attr("target"),c=$("#"+c);a.addClass("userMenu_buttonActive").siblings().removeClass("userMenu_buttonActive");$(".userMenuContent").hide();c.show()});var a="";$("#uploadData_form").on("submit",
function(a){a.preventDefault&&a.preventDefault();return!1});$("#uploadData_input").change(function(){$("#uploadData_error").html("");$("#uploadData_confirm, #uploadData_error, #geocoding_loading").hide();$("#uploadData_description, #uploadData_loading").show();""==$(this).val()?$("#uploadData_loading").hide():$("#uploadData_form").ajaxSubmit({dataType:"json",success:function(b){if(b&&b.status&&"error"==b.status){$("#uploadData_description, #uploadData_loading, #uploadData_confirm ul").hide();$("#uploadData_confirm").show();
var c="";$.each(b.msg.split("<br>"),function(a,b){c=0==a?c+("<h3>"+b+"</h3>"):c+(b+"<p></p>")});$("#uploadData_error").html(c).show()}else{var d=b.rowCount;calculateCredit(d);var e=$("#uploadData_field"),f=b.jsonCols,g="",m="";a=b.fileName;for(b=0;b<f.length;b++){var h=f[b].name;f[b].suggested?g+='<input type="checkbox" name="'+h+'" id="'+h+'" checked ><label for="'+h+'">'+h+"   <span style='color: red;'>[Suggested field: "+f[b].suggested+"]</span></label>":m+='<input type="checkbox" name="'+h+'" id="'+
h+'"><label for="'+h+'">'+h+"</label>"}c="<fieldset data-role='controlgroup' data-mini='true'><legend>Select geocoding columns:</legend>"+g+m+"</fieldset>";e.html(c).trigger("create");var k="x y lat lon latitude longitude geo coordinates coordinate".split(" ");e.find("input:checked").each(function(){-1!=$.inArray(this.id,k)?calculateCredit(d,!0):calculateCredit(d)});e.find("input[type='checkbox']").click(function(){calculateCredit(d);e.find("input:checked").each(function(){-1!=$.inArray(this.id,k)&&
calculateCredit(d,!0)})});$("#uploadData_description, #uploadData_loading").hide();$("#uploadData_confirm").show()}},error:function(a){console.log(a.responseText)}})});$("#submit_button").click(function(){var b=$.map($("#uploadData_field input:checked"),function(a){return a.id});if($("#uploadData_agreementCheck").prop("checked")){$("#geocoding_loading").show();var c=Date.now();$.ajax({dataType:"json",url:"python/retrieveAndGeocode.py",data:{fileName:a,geoColumns:b,username:app.userInfo.email,oauth:app.userInfo.oauth},
success:function(b){if(b&&b.status&&"error"==featureCollections.status)console.log(b.msg);else{var e=Date.now(),e=Math.round((e-c)/1E3);app.userInfo.city&&app.userInfo.country&&_gaq.push(["_trackEvent","ProcessTime",app.userInfo.country,app.userInfo.city,e]);e=$("#uploadData_input").val().split(".");(e=e[e.length-1])&&""!=e&&_gaq.push(["_trackEvent","Data","Format-"+e,app.userInfo.email]);$("#dialog_uploadData").popup("close");!b||0>=b.features.length?alert("No rows could be geocoded.  Please make sure you have selected the correct location column."):
(clearLayers(),app.geocodingResult={type:"GEOJSON",json:b,srs:"EPSG:4326",title:a,keywords:["testing"],column:{statistics:""},downloadLink:b.URL_xls&&""!=b.URL_xls?b.URL_xls:null,dataID:b.dataID,hasGeomask:b.features[0].geomasked_geometry?!0:!1},showTable(app.geocodingResult),updateAccountInfo(app.userInfo.email),$("#geocoding_loading").hide())}},error:function(a){console.log("Error:");console.log(a.responseText)}})}else alert("You must agree to the PathGeo agreement before your data is geocoded.")});
$("#layer_selector").hide()}
function calculateCredit(a,b){var c=app.userInfo.credit,d=b?Math.round(a/10):a,e=c-d,f=null;$("#uploadData_controls").show();$("#submit_button").val("Map Your Data (All records)");0==c&&$("#uploadData_controls").hide();if(0>e){var g=b?10*c:c,e="<font style='color:#FF0000; font-weight:bold;'>"+e+"</font>",f="Only top "+g+" will be geocoded!<br>Or buy some credits to geocode all records.";$("#submit_button").val("Map Your Data (Only top "+g+" records)")}$("#uploadData_yourCredit").html(c);$("#uploadData_rowCount").html(a);
$("#uploadData_neededCredit").html(d);$("#uploadData_balance").html(e);$("#uploadData_balanceMsg").html(f)}function showSumup(a){var b="<option value='none'>Please choose..</option>";$.each(a.features[0].properties,function(a,d){isNaN(d)||(b+="<option value='"+a+"'>"+a+"</option>")});$("#sumup_select").html(b).selectmenu("refresh");setTimeout(function(){$("#dialog_sumup").popup("open")},200)}
function resizeMap(a,b){$("#div_map").animate(a,500,function(){app.map.invalidateSize(!1);$("#dataPanel").css(b);$(".dataTables_scrollBody").css({height:app.css.dataTable_height()})})}
function sumup(a){var b=$("#sumup_select").val();app.geocodingResult.column.statistics="";"none"!=b&&!0!=a&&(app.geocodingResult.column.statistics=b);showTable(app.geocodingResult);$(".ui-dialog").dialog("close");setTimeout(function(){$("#uploadData_description").show();$("#uploadData_confirm, #uploadData_controls").hide();$("#dialog_sumup").popup("close");$("#uploadData_agreementCheck").attr("checked",!1).checkboxradio("refresh");$("#uploadData_input").val("");$("#geocoding_loading").hide()},100)}
function changeMarkerIcon(a,b,c){var d=new L.icon({iconUrl:a,iconSize:[b,c],iconAnchor:[b/2,c/2]}),e=L.icon;a=1<a.split("bullet").length?"images/1374590745_bullet-red.png":"images/marker/Magenta/5.png";var f=new e({iconUrl:a,iconSize:[b,c],iconAnchor:[b/2,c/2]});$.each(app.geocodingResult.geoJsonLayer._layers,function(a,b){b.setIcon(d);b.options.iconDefault=d;b.options.iconHover=f});app.highlightMarker&&app.highlightMarker.setIcon(f)}
function showLayer(a,b){function c(a){b.isShow&&($.each(a.layers,function(a,c){c.addTo(app.map);app.showLayers.push(c);b.isFilter&&c.options.layerName&&$(".leaflet-control-mapGallery ul li[layer='"+c.options.layerName+"']").css("background-color",app.css.mapGalleryHighlightColor)}),b.zoomToExtent&&app.map.fitBounds(a.geoJsonLayer.getBounds()),b.callback&&b.callback());$("#img_loading").hide();$(".leaflet-control-mapGallery").show();b.isFilter||$("#mapPopup_geoJsonLayer").show()}b||(b={});b.isShow=
"undefined"===typeof b.isShow?!1:b.isShow;b.zoomToExtent="undefined"===typeof b.zoomToExtent?!0:b.zoomToExtent;b.isFilter="undefined"===typeof b.isFilter?!1:b.isFilter;a.title&&$("#lbl_dataName").html(a.title);a.featureCount=0;a.layers=[];clearLayers();switch(a.type){case "GEOJSON":var d=function(a){e(a);c(a);$('.leaflet-control-mapGallery ul li[layer="geoJsonLayer"]').css("background-color","#5B92C0");$("#dialog_uploadData").popup("close")},e=function(a){var c=[],d={},e=a.column.statistics||null,
k=null,n=null;if(b.isFilter)var l=a.geoJsonLayer._layers,k=l[Object.keys(l)[0]].options.icon;a.geoJsonLayer=new L.geoJson(a.json,{onEachFeature:function(b,k){var r=pathgeo.util.objectToHtml(b.properties,["_featureID","_rowID"]),r=pathgeo.util.highlightKeyword(a.keywords,r);k.bindPopup(r,{maxWidth:500,maxHeight:300});if(0<=b.properties._featureID&&(r=b.properties._featureID,c[r]=k,b.properties[app.zipcodeFieldName])){var n=b.properties[app.zipcodeFieldName],l=parseFloat(b.properties[e]);if(d[n]){var q=
d[n].feature.properties;q["extra-ids"].push(r);q["extra-count"]+=1;q["extra-"+e+"_sum"]+=l}else if(app.layers.demographicData&&app.layers.demographicData.zipcodes[n]){var p=app.layers.demographicData.zipcodes[n],q=p.feature.properties;q["extra-ids"]=[r];q["extra-count"]=1;q["extra-"+e+"_sum"]=l;d[n]=p}}k.on({mouseover:function(a){showLocalInfo(a.target.feature.properties._featureID,{scrollToRow:!0,zoomToCenter:!1,showPopup:!1})},mouseout:function(a){},click:function(a){showLocalInfo(a.target.feature.properties._featureID,
{scrollToRow:!0,zoomToCenter:!1})},dragend:function(a){},drag:function(a){}})},style:{},pointToLayer:function(a,b){app.geomask&&a.geomasked_geometry&&(coords=a.geomasked_geometry.coordinates,b=new L.LatLng(coords[1],coords[0]));var c=n=new L.icon({iconUrl:"images/marker/blue/5.png",iconSize:[16,21.6],iconAnchor:[8,10.8]}),d=new L.icon({iconUrl:"images/marker/Magenta/5.png",iconSize:[16,21.6],iconAnchor:[8,10.8]});return new L.marker(b,{icon:k?k:c,iconHover:d,iconDefault:c,draggable:!0})},filter:function(a){a=
a.geometry.coordinates;return 0!=a[0]&&0!=a[1]&&-1!=a[0]&&-1!=a[1]?!0:!1},layerName:"geoJsonLayer"});a.geoJsonLayer.layers=c;l=$.map(d,function(a,b){return a});l.sort(function(a,b){return b.feature.properties["extra-count"]-a.feature.properties["extra-count"]});$.each(l,function(a,b){b.feature.properties["extra-count-rank"]=a+1});e&&""!=e&&(l.sort(function(a,b){return b.feature.properties["extra-"+e+"_sum"]-a.feature.properties["extra-"+e+"_sum"]}),$.each(l,function(a,b){b.feature.properties["extra-"+
e+"_sum-rank"]=a+1}));$.each(d,function(a,b){b.on("click",function(a){showBusinessAction("top_users")})});a.zipcodeLayer=d;app.controls.toc.addOverlay(a.geoJsonLayer,"Marker Map");a.markerClusterLayer=pathgeo.layer.markerCluster(a.json,{onEachFeature:function(a,b){b.on({mouseover:function(a){},click:function(a){showLocalInfo(a.target.feature.properties._featureID,{scrollToRow:!0,zoomToCenter:!1})}})},pointToLayer:function(a,b){return new L.marker(b,{icon:k?k:n})},layerName:"markerClusterLayer"},{clusterclick:function(b){if(b.layer._popup)b.layer.openPopup();
else{var c=pathgeo.util.readClusterFeatureProperies(b.layer,[]),d="<div class='popup'>There are <b>"+b.layer._childCount+"</b> twitters:<p></p><ul>";$.each(c,function(b,c){d+="<li><img src='images/1359925009_twitter_02.png' width=20px />&nbsp; &nbsp; <b>"+c[a.fieldName.username]+"</b>: "+c[a.fieldName.text]+"</li>"});d+="</ul></div>";d=d.replace(/undefined/g,"Tweet");d=pathgeo.util.highlightKeyword(a.keywords,d);b.layer.bindPopup(d,{maxWidth:500,maxHeight:300}).openPopup()}}});app.controls.toc.addOverlay(a.markerClusterLayer,
"Cluster Map");var p=null;b.isFilter&&(p=a.heatMapLayer.options.radius.value);var s=app.map.getBoundsZoom(a.geoJsonLayer.getBounds()),l=function(a){a=6.25*Math.pow(2,17-s+a);a=5E3<=a?5E3:a;return p?p:50<=a?a:50};a.heatMapLayer=pathgeo.layer.heatMap(a.json,l(0),{opacity:0.55,layerName:"heatMapLayer"});app.controls.toc.addOverlay(a.heatMapLayer,"Heat Map");b.isFilter||($("#heatmap_slider").attr({min:50,max:3050,step:60,value:l(0)}).on("slidestop",function(a){a=a.currentTarget.value;var b=app.geocodingResult;
b.heatMapLayer._map&&app.map.removeLayer(b.heatMapLayer);app.controls.toc.removeLayer(b.heatMapLayer);b.heatMapLayer=pathgeo.layer.heatMap(b.json,a,{opacity:0.55,layerName:"heatMapLayer"});b.heatMapLayer.addTo(app.map);app.controls.toc.addOverlay(b.heatMapLayer,"Heat Map")}).keypress(function(a){return!1}).slider("refresh"),$("#heatmap_radius .ui-input-text").html("Change Hot Spot's Radius (unit: Feet)"));0==a.showLayerNames.length&&a.showLayerNames.push("geoJsonLayer");$.each(a.showLayerNames,function(b,
d){a.layers.push(a[d])})};a.json?d(a):$.getJSON(a.url,function(b){a.json=b instanceof Array?{type:"FeatureCollection",features:b}:b;d(a)});break;case "WMS":a.param&&a.param.layers&&(a.param.format=a.param.format||"image/png",a.param.transparent=a.param.transparent||!0,a.layers.push(L.tileLayer.wms(a.url,a.param)),a.layers[0].on("load",function(a){console.log("loaded")}),c(a),app.controls.toc.addOverlay(a.layers[0],a.name))}}
function switchVisualization(a){removeLayers();var b;$.each(a,function(a,d){switch(d){case "MARKERCLUSTER":b=app.geocodingResult.markerClusterLayer.addTo(app.map);break;case "HEATMAP":b=app.geocodingResult.heatMapLayer.addTo(app.map);break;case "GEOJSON":b=app.geocodingResult.geoJsonLayer.addTo(app.map)}app.showLayers.push(b);_gaq.push(["_trackEvent","Visualization",d,app.userInfo.email])})}
function removeLayers(){0<app.showLayers.length&&($.each(app.showLayers,function(a,b){app.controls.toc._layers[b._leaflet_id]&&app.controls.toc.removeLayer(b);app.map.removeLayer(b)}),app.showLayers=[])}
function clearLayers(){var a=app.geocodingResult;a.showLayerNames=[];$.each(["geoJsonLayer","markerClusterLayer","heatMapLayer"],function(b,c){var d=a[c];d&&(d._map&&(a.showLayerNames.push(c),app.map.removeLayer(d),$(".leaflet-control-mapGallery ul li[layer='"+c+"']").css("background-color","")),app.controls.toc.removeLayer(d))});app.highlightMarker&&app.map.removeLayer(app.highlightMarker)}function switchBaseLayer(a){app.map.hasLayer(a)?app.map.removeLayer(a):a.addTo(app.map)}
function showTable(a,b){function c(a){a.dataTable||(a.dataTable=pathgeo.util.geojsonPropertiesToArray(a.json,{statisticsColumn:a.column.statistics}));var c=a.dataTable,f=["Coordinates","latitude","longitude"];$.each(c.columns_dataTable,function(a,b){$.each(f,function(a,c){c==b.sTitle&&("Coordinate"==c&&(b.bVisible=!1),b.bSearchable=!1,b.bSortable=!1)})});app.dataTable&&(app.dataTable.fnDestroy(),$(".dataTable_nav, #dataTable_control, #dataTable").html(""));app.dataTable=$("#dataTable").dataTable({bDestroy:!0,
aaData:c.datas,aoColumns:c.columns_dataTable,bJQueryUI:!1,bAutoWidth:!0,bPaginate:!1,sPaginationType:"two_button",sScrollY:app.css.dataTable_height(),sScrollX:"100%",bDeferRender:!0,oLanguage:{sSearch:""},iDisplayLength:1E3,sDom:'<"dataTable_toolbar"<"dataTable_nav"><"dataTable_tools"if><"dataTable_menu"<"infobox_triangle"><"infobox">>><"dataTable_table"rtS<>>',fnInitComplete:function(c,e){var f=0,g;$("#"+c.sTableId+"_filter input").attr({title:"Filter data results by keyword",placeholder:"Filter data results by keyword"}).prop("type",
"search").textinput().unbind("keypress keyup").bind("keypress keyup",function(a){var b=$(this);f=0;g||(g=setInterval(function(){3<=f&&(clearInterval(g),g="",searchTerm=$(b).val(),app.dataTable.fnFilter(searchTerm),f=0);f++},100))});setTimeout(function(){a.defaultJSON||(a.defaultJSON=a.json);app.dataTable.fnAdjustColumnSizing();app.$tr=$(".dataTable tr");showLayer(a,{isShow:!0,callback:b.callback});showDataTableChart(a.json);$("#showhideTable").show();$(".dataTables_scrollHeadInner table").css({top:"0px"});
resizeMap({height:"75%"},{height:"25%"})},50)},fnRowCallback:function(b,c,e,f){void 0==$(b).attr("_featureID")&&($(b).attr({_featureID:f,_rowID:f}),b=a.json.features[f].properties,b._featureID=f,b._rowID=f)},fnDrawCallback:function(b){if($(".dataTables_filter input").is(":focus")){b=$("#dataTable_info");var c=b.html(),e=c.split("(filtered");0<e.length&&e[1]?b.html(c).css({"margin-top":"2px"}):b.css({"margin-top":"13px"});var f=this,g=a.defaultJSON.features,p={type:"FeatureCollection",features:[]},
s,t=f.$("tr",{filter:"applied"});app.layers.demographicData&&app.map.removeLayer(app.layers.demographicData);var u=$("#dataTable tr");$.each(app.css.dataTable_highlightRow,function(a,b){u.css(a,"")});setTimeout(function(){if(f.$("tr",{filter:"applied"}).length==t.length){var b={},c="",e=[];f.$("tr",{filter:"applied"}).each(function(a,d){s=g[this._DT_RowIndex];s.properties._rowID=a;p.features.push(s);e.push(this._DT_RowIndex);(c=s.properties[app.zipcodeFieldName])&&(b[c]=b[c]?b[c]+1:1)});a.filterRowID=
e.join(",");a.filterTerm=$(".dataTables_filter input").val();b=$.map(b,function(a,b){return b});0<p.features.length&&(a.json=p,showLayer(a,{isShow:!0,isFilter:!0}),showDataTableChart(a.json),0<b.length&&f.$("tr",{filter:"applied"}).length==g.length&&(app.layers.selectedZipcodeLayer&&app.map.hasLayer(app.layers.selectedZipcodeLayer))&&(app.map.removeLayer(app.layers.selectedZipcodeLayer),app.layers.selectedZipcodeLayer.clearLayers()))}},0)}}});app.dataTable.columns=c.columns;var g="<ul>"+(a.downloadLink?
"<li><img src='images/1365858910_download.png' title='download'/><span>Download</span></li>":"")+"<li><img src='images/1365859564_3x3_grid_2.png' title='show / hide columns'/><span>Show/hide Columns</span></li>"+(a.hasGeomask?"<li><img src='images/1376481601_Security.png' title='geomask'/><span>GeoMask</span></li>":"")+"<li><img src='images/1375655879_br_up.png' title='More Table'/><span>More Table</span></li></ul>";$(".dataTable_tools").append(g).find("ul li").click(function(){var a=$(this),b=a.find("img"),
a=a.find("span"),c=b.attr("title");switch(c){case "download":$("#downloadType_all_geomask, #downloadType_selected, #downloadType_selected_geomask").checkboxradio("disable");app.geomask&&$("#downloadType_all_geomask").checkboxradio("enable");app.geocodingResult.filterRowID&&app.geocodingResult.filterTerm&&($("#downloadType_selected").checkboxradio("enable"),app.geomask&&$("#downloadType_selected_geomask").checkboxradio("enable"));$("#dialog_download").popup("open");break;case "print":print();break;
case "show / hide columns":showInfobox(c,{left:$(this).offset().left,top:$(this).offset().top-25},this);break;case "More Table":b.attr({title:"Less Table",src:"images/1375655890_br_down.png"});a.html("Less Table");resizeMap({height:"47.5%"},{height:"52.5%"});break;case "Less Table":b.attr({title:"More Table",src:"images/1375655879_br_up.png"});a.html("More Table");resizeMap({height:"75%"},{height:"25%"});break;case "geomask":$("#dialog_geomask").popup("open")}_gaq.push(["_trackEvent","Tools_dataTable",
c,app.userInfo.email])});$(".dataTable_nav").html($("#dataTable_nav").html());$("#dataTable_control").html($(".dataTable_toolbar"));$("#dataTable tr:not([role='row'])").on({click:function(){showLocalInfo($(this).context._DT_RowIndex,{scrollToRow:!1,zoomToCenter:!0})},mouseover:function(){}});g="";$.each(c.columns,function(a,b){g+="<option>"+b+"</option>"});c=function(){showDataTableChart(a.json)};$("#dataTable_chart #select_x").append(g).change(c).val("name").change();$("#dataTable_chart #select_y").append(g).change(c).val(app.geocodingResult.column.statistics).change();
$(".dataTable_chartType").click(c);showInfoPanel("dataPanel",$("#menuToolbox ul li:first-child")[0])}b||(b={});b.callback=b.callback||null;$("#dataPanel_intro").hide();app.layers.selectedZipcodeLayer&&app.map.hasLayer(app.layers.selectedZipcodeLayer)&&(app.map.removeLayer(app.layers.selectedZipcodeLayer),app.layers.selectedZipcodeLayer.clearLayers());app.highlightMarker&&app.map.removeLayer(app.highlightMarker);a.json?c(a):$.getJSON(a.url,function(b){a.json=b instanceof Array?{type:"FeatureCollection",
features:b}:b;c(a)})}
function showInfobox(a,b,c){$(c);var d=a+"<br><ul>";switch(a){case "show / hide columns":$.each(app.dataTable.columns,function(a,b){var c=0<$(".dataTable th:contains('"+b+"')").length?"checked":"";d+="<li><input type='checkbox' id="+a+" "+c+" onclick='app.dataTable.fnSetColumnVis(this.id, this.checked); ColVis.fnRebuild(app.dataTable);' />&nbsp; &nbsp; "+b+"</li>"});break;case "demographic data":$.each(app.demographicData,function(a,b){d+="<li><input type='radio' name='demographic' value="+a+" onclick='if(this.checked){app.layers.demographicData.redrawStyle(this.value); app.layers.demographicData.addTo(app.map);}' />&nbsp; &nbsp; "+
b+"</li>"});break;case "map gallery":$.each([{label:"marker map",value:"GEOJSON",layerName:"geoJsonLayer"},{label:"cluster map",value:"MARKERCLUSTER",layerName:"markerClusterLayer"},{label:"heat map",value:"HEATMAP",layerName:"heatMapLayer"}],function(a,b){d+="<li><input type='radio' name='mapGallery' value='"+b.value+"' "+(app.geocodingResult[b.layerName]._map?"checked=checked":"")+" onclick='if(this.checked){switchVisualization([this.value]);}' />&nbsp; &nbsp; "+b.label+"</li>"});break;case "canned report":$.each(["demographic data report",
"social media report"],function(a,b){d+="<li><input type='radio' name='mapGallery' value='"+b+"'  onclick='' />&nbsp; &nbsp; "+b+"</li>"});break;case "print":window.print();return}d+="</ul>";$(".dataTable_menu .infobox").html(d);$(".dataTable_menu").css(b).show()}
function showLocalInfo(a,b){var c=app.geocodingResult.geoJsonLayer.layers[a];if(c){var d=c.feature,e=d.properties[app.zipcodeFieldName];b||(b={});b.scrollToRow=b.scrollToRow||!1;b.zoomToCenter=b.zoomToCenter||!1;b.showPopup=b.showPopup||!1;app.map.closePopup();b.scrollToRow&&(d=d.properties._rowID,app.dataTable.fnSettings().oScroller.fnScrollToRow(d,!1));b.zoomToCenter&&(d=c._latlng,app.map.setView(new L.LatLng(d.lat,d.lng-0.0025),14));b.showPopup&&c.openPopup();$.each(app.css.dataTable_highlightRow,
function(a,b){app.$tr.css(a,"")});app.$tr.closest("[_featureID="+a+"]").css(app.css.dataTable_highlightRow);app.highlightMarker.setIcon(c.options.iconHover).setLatLng(c.getLatLng()).addTo(app.map);$("#businessActions_type").attr("zipcode",e);$("#demographic_type div[data-role='collapsible'] h3").attr("value")}else alert("The coordinates (-1, -1) is not correct. Please select other data. ")}
function highlightZipcode(a,b){$("#zipcodePanel").show();b||(b={});b.zoomToBounds=b.zoomToBounds||!1;var c=app.layers.selectedZipcodeLayer;c&&app.map.hasLayer(c)&&(app.map.removeLayer(c),c.clearLayers());c=new L.featureGroup;$.each(a,function(b,e){var f=app.geocodingResult.zipcodeLayer[e];c.addLayer(f);if(1==a.length){var g=f.feature.properties,f=g["extra-count"],m=g["extra-count-rank"],h=app.geocodingResult.column.statistics,k=g["extra-"+h+"_sum"]||null,g=g["extra-"+h+"_sum-rank"]||null,n=h?app.geocodingResult.dataTable.statisticsColumn[h].sum:
null;$("#zipcodePanel h1").html("zipcode: "+a[0]);$("#zipcodePanel img").click(function(){showBusinessAction("top_users")});$("#zipcode_summary").html("Total Customers: "+f+" <font class='rank'>Rank #"+m+"</font>");k&&(n&&g)&&$("#zipcode_summary").append("<p>Total "+h+": "+parseFloat(k).toFixed(2)+" ("+parseFloat(100*(k/n)).toFixed(2)+"%) <font class='rank'>Rank#"+g+"</font>")}});c.addTo(app.map).bringToBack();app.layers.selectedZipcodeLayer=c;b.zoomToBounds&&app.map.fitBounds(c.getBounds())}
function showBusinessAction(a){var b=app.geocodingResult.zipcodeLayer,c=$("#businessActions_type").attr("zipcode"),d=app.geocodingResult.json.features.length;dataArray=[];sort=[{column:1,desc:!0}];chartOptions={googleChartWrapperOptions:{chartType:"BarChart",containerId:"businessActions_result",view:{columns:[0,1]},options:{width:$("#businessActions_select").width(),height:$("#businessActions_select").height()-50,title:"",titleX:"",titleY:"",legend:"none",chartArea:{width:"65%",height:"85%",top:10},
fontSize:11,isStacked:!0,series:{0:{color:"#5B92C0",visibleInLegend:!0}},vAxes:{0:{titleTextStyle:{color:"#222222"},textStyle:{color:"#222222"}}},hAxes:{0:{titleTextStyle:{color:"#222222"},textStyle:{color:"#222222"}}},backgroundColor:{fill:"transparent"},tooltip:{isHtml:!0},is3D:!0}},callback:null,callback_mouseover:null,callback_mouseout:null,callback_select:function(a){a=a.data.getValue(a.row,0);showDemographicData(a)}};switch(a){case "top_users":dataArray=new google.visualization.DataTable;dataArray.addColumn("string",
"zipcodes");dataArray.addColumn("number","customers");dataArray.addColumn({type:"string",role:"tooltip",p:{html:!0}});dataArray.addColumn("number","highlight");dataArray.addColumn({type:"string",role:"tooltip",p:{html:!0}});dataArray.addColumn("number","originalCustomers");var e=0,f=0,g="",m=0;$.each(b,function(a,b){m=b.feature.properties["extra-count"];e=0;f=m;a==c&&(e=m,f=0);g="<div id='chartTooltip'><b>Zipcode: </b>"+a+"<br><b>Customers: </b>"+m+" ("+100*(m/d).toFixed(4)+"%)</div>";dataArray.addRow([a,
f,g,e,g,m/d])});sort=[{column:5,desc:!0}];chartOptions.googleChartWrapperOptions.options.series[1]={color:"#ED3D86",visibleInLegend:!1};chartOptions.googleChartWrapperOptions.options.series[2]={color:"transparent",visibleInLegend:!1};chartOptions.googleChartWrapperOptions.options.titleX="The number of customers";chartOptions.googleChartWrapperOptions.options.titleY="Zip Codes";break;case "top_sales":var h=app.geocodingResult.column.statistics;dataArray=[["zipcodes","sum_"+h+""]];$.each(b,function(a,
b){dataArray.push([parseInt(a),b.feature.properties["extra-"+h+"_sum"]])});chartOptions.googleChartWrapperOptions.options.titleX="The sum of "+h;chartOptions.googleChartWrapperOptions.options.titleY="Zip Codes"}pathgeo.service.drawGoogleChart(dataArray,[chartOptions],null,null,{sort:sort});$("#dialog_businessAction").popup("open")}
function showDemographicData(a){var b=app.layers.demographicData.zipcodes[a].feature.properties;$("#businessActions_type").attr("zipcode",a).change();$("#businessActions_detailTitle").text(b.NAME);highlightZipcode([a],{zoomToBounds:!0});$.each(b,function(a,b){a.split("extra-")});$("#businessActions_detailContent_collapsible div.ui-btn-inner a").on("click",function(b,d){if(app.layers.demographicData){var e=app.layers.demographicData,f=$(this).attr("value");e.redrawStyle(f,function(b){var c=e.options.styles(b,
f);b.properties.ZIP==a&&(c.width=4,c.color="#666",c.dashArray="");console.log(c);return c});e.addTo(app.map);$(".leaflet-control-legend").html(e.getLegend(f))}});$("#businessActions_detailContent_collapsible div.ui-collapsible h4").on("click",function(a,b){$(this).hasClass("ui-collapsible-heading-collapsed")||$(this).attr("value")});$("#dialog_businessAction").popup("close")}
function showDemographicChart(a,b,c){var d=[["type","value"]];d.push([String(b),app.properties[b][a]]);d.push(["CA Average",app.properties_average[a]]);a={googleChartWrapperOptions:{chartType:"ColumnChart",containerId:c,view:{columns:[0,1]},options:{width:$("#"+c).width(),height:$("#"+c).height(),title:"",titleX:"Type",titleY:"Value",legend:"none",backgroundColor:{fill:"transparent"}}},callback:null,callback_mouseover:null,callback_mouseout:null,callback_select:function(a){console.log(a)}};pathgeo.service.drawGoogleChart(d,
[a],null,null)}
function showDataTableChart(a){var b=$("#dataTable_chart #select_x").val(),c=$("#dataTable_chart #select_y").val(),d=$(".dataTable_chartType:checked").val();b&&c?"none"!=b&&"none"!=c&&(d={googleChartWrapperOptions:{chartType:d,containerId:"dataTable_chartContent",view:{columns:[0,1]},options:{width:$(".infoPanel").width()-20,height:30*a.features.length,title:"",titleX:b,titleY:c,legend:{position:"top"},chartArea:{width:"",height:"90%",top:20},fontSize:11,vAxes:{0:{titleTextStyle:{color:"#ffffff"},textStyle:{color:"#ffffff"}}},
hAxes:{0:{titleTextStyle:{color:"#ffffff"},textStyle:{color:"#ffffff"}}},backgroundColor:{fill:"transparent"}}},callback:null,callback_mouseover:function(a){showLocalInfo(a.value.properties._featureID,{scrollToRow:!0,zoomToCenter:!0,showPopup:!0})},callback_mouseout:null,callback_select:function(a){showLocalInfo(a.value.properties._featureID,{scrollToRow:!0,zoomToCenter:!0,showPopup:!0})}},pathgeo.service.drawGoogleChart(a,[d],[b,c],null)):alert("Please select the x and y axis first")}
function showLocalInfoChart(a,b){pathgeo.service.drawGoogleChart(a,[{googleChartWrapperOptions:{chartType:"ColumnChart",containerId:b,view:{columns:[0,1]},options:{width:300,height:200,title:"",titleX:"",titleY:"",legend:"",vAxes:{0:{titleTextStyle:{color:"#ffffff"},textStyle:{color:"#ffffff"}}},hAxes:{0:{titleTextStyle:{color:"#ffffff"},textStyle:{color:"#ffffff"}}},backgroundColor:{fill:"transparent"}}},callback:null,callback_mouseover:null,callback_mouseout:null,callback_select:function(a){console.log(a)}}],
null,null)}function showZipcodeChart(a,b,c,d){var e={googleChartWrapperOptions:{chartType:"PieChart",containerId:a,view:{columns:[0,1]},options:{width:300,height:200,title:"",titleX:"",titleY:"",legend:"",backgroundColor:{fill:"transparent"}}},callback:null,callback_mouseover:null,callback_mouseout:null,callback_select:null},f=[["zipcode","value"],[b,c],["others",d-c]];setTimeout(function(){pathgeo.service.drawGoogleChart(f,[e],null,null)},10)}
function searchBusinessIntelligent(a){console.log(a)}
function showDemo(a){var b=null;$("#uploadData_loading").show();clearLayers();switch(a){case "SAN FRANCISCO":b={url:"db/demo-SanFrancisco.json",title:"[DEMO] San Francisco shoes customer",column:{statistics:"sales"},keywords:[]};break;case "SAN DIEGO":b={url:"db/demo-SDcrime.json",title:"[DEMO] San Diego Crime data",column:{statistics:"type"},downloadLink:"./geocoded_files/incidents-2013-small.csv",keywords:[],dataID:"1375413042"};break;case "SD-NAVAJO":b={url:"db/demo-SD-Navajo-201207-09.json",title:"San Diego Navajo Crime rate (2012/07~09)",
column:{statistics:"type"},downloadLink:"./geocoded_files/2012-crime-navajo-three-month-7-9.xls",keywords:[],dataID:"1377287606"};break;case "SD-PACIFIC-BEACH":b={url:"db/demo-SD-PacificBeach-201207-09.json",title:"San Diego Pacific Beach Crime rate (2012/07~09)",column:{statistics:"type"},downloadLink:"./geocoded_files/2012-crime-pacific-beach-three-month-7-9.xls",keywords:[],dataID:"1377287686"}}b&&$.getJSON(b.url,function(a){b.geojson=a;b.type="GEOJSON";b.hasGeomask=a.features[0].geomasked_geometry?
!0:!1;app.geocodingResult=b;$("#uploadData_loading").hide();$("#dialog_uploadData").popup("close");showTable(app.geocodingResult,{callback:function(){}})});_gaq.push(["_trackEvent","Data","Sample-"+a,app.userInfo.email])}
function showInfoPanel(a,b){$("#menuToolbox ul li").css("background","");$(b).css("background","rgba(255,255,255,0.3)");$(".infoPanel").hide();$("#"+a).show();$("#content").width();$(".infoPanel").width();$("#menuToolbox").width();$("#content").width();app.map.invalidateSize(!1)}function closeInfoPanel(){$("#menuToolbox ul li").css("background","");$(".infoPanel").hide();$("#div_map").css({width:"100%"});app.map.invalidateSize(!1)}function showDialog(a){$("#"+a).popup("open")}
function logout(){$("#header_login").attr("href","#dialog_login").off("click").find(".ui-btn-text").html("Log in");$.removeCookie("PathGeo",{path:"/"});location.reload()}
function afterLogin(a){$("#dialog_login").popup("close");$("#header_login").attr("href","#").click(function(){$userPopupMenu=$("#userPopupMenu");$userPopupMenu.is(":visible")?$("#userPopupMenu").hide():$("#userPopupMenu").show()}).find(".ui-btn-text").html("Account");$("#header a[href='#dialog_uploadData'], #header_tutorial").show();$("#uploadData_username").attr("value",a);$("#uploadData_oauth").attr("value",app.userInfo.oauth);setTimeout(function(){$("#dialog_uploadData").popup("open")},500)}
function getAccountInfo(a,b){$.ajax({url:"common/ws/queryAccount.py",data:{email:a,oauth:app.userInfo.oauth},dataType:"json",success:function(a){a&&(a.status&&"ok"==a.status&&a.account)&&writeAccountInfo(a.account,b)},error:function(a){console.log("[ERROR]getAccountInfo: "+a.responseText)}})}
function writeAccountInfo(a,b){$.each(a,function(a,b){a in app.userInfo&&(app.userInfo[a]=b)});b||(afterLogin(app.userInfo.email),$("#userMenu_iframe").attr("src","common/accountManagement.html?email="+app.userInfo.email+"&oauth="+app.userInfo.oauth));refreshAccountInfo()}function updateAccountInfo(a){getAccountInfo(a,!0)}
function refreshAccountInfo(){var a={userPopupMenu_username:app.userInfo.email,userPopupMenu_credit:"Credit: "+app.userInfo.credit,userPopupMenu_accountType:app.userInfo.accountType.toUpperCase()};$.each(a,function(a,c){$("#"+a).html(c)})}function showOauth(a){$("#dialog_login").popup("close");if("google"==a||"facebook"==a)app.oauthWindow=window.open("ws/oauth.py?provider="+a,a,"width=800,height=600,left=50,top=50,toolbar=1,status=1")}
function print(){var a='<html><head><link rel="stylesheet"  href="js/leaflet/leaflet.css" /><link rel="stylesheet"  href="css/main.css" /><link rel="stylesheet"  href="css/jquery.dataTables.css" /><style type="text/css">.leaflet-top {display:none;} .leaflet-right {display:none;} #showhideTable {display:none;} } </style></head><body style="background:#ffffff;">'+$("#div_map")[0].innerHTML+"</body></html>",b=window.open("","MapTime","width=800,height=600,top=0,left=0,toolbar=yes,scrollbars=yes,status=yes,resizable=yes");
b.document.writeln(a);b.document.close();b.focus();b.print()}function showProfile(a){a||(a="account");$("#userMenu_iframe").attr("src","common/accountManagement.html?email="+app.userInfo.email+"&oauth="+app.userInfo.oauth+"&tab="+a);$("#dialog_userMenu").popup("open")}function getClientGeo(){geoip2.city(function(a){app.userInfo.city=a.city.names.en;app.userInfo.country=a.country.iso_code},function(a){console.log("[ERROR]getClientGeo: "+a.code+"="+a.error)})}
function download(){var a=$('#dialog_download input[name="downloadType"]:checked').val(),b=1<a.split("geomask").length?!0:!1;if("all"==a)window.open(app.geocodingResult.downloadLink),$("#dialog_download").popup("close");else{var c=null,d=null,e=app.geocodingResult;e.filterRowID&&(e.filterTerm&&""!=e.filterTerm&&"all+geomask"!=a)&&(c=e.filterRowID,d=e.filterTerm);$("#download_loading").show();$.ajax({url:"python/filterUploadData.py",data:{username:app.userInfo.email,oauth:app.userInfo.oauth,table:app.geocodingResult.dataID,
rows:c,term:d,geomask:b},dataType:"json",type:"POST",success:function(a){a&&(a.URL_xls&&""!=a.URL_xls)&&(window.open(a.URL_xls),$("#download_loading").hide(),$("#dialog_download").popup("close"))},error:function(a){console.log("[ERROR] download: "+a.responseText)}})}}function oauth_callback(a){app.oauthWindow.close();$.cookie("PathGeo",{email:a.email,oauth:a.oauth},{expires:7,path:"/"});writeAccountInfo(a)}
function readTutorial(){$.getJSON("db/tutorial.json",function(a){app.tutorial=a;app.introJS=introJs("#pageMap");app.introJS.setOptions({steps:a}).onchange(function(a){}).oncomplete(function(){console.log("tutorial complete")})})}function showTutorial(){app.dataTable?app.introJS.start():alert("Please upload data first or check out our sample data!")}
function geomask(){var a=$("#dialog_geomask input[name='geomaskType']:checked").val();app.geomask=!1;"geomask"==a&&(app.geomask=!0);showLayer(app.geocodingResult,{isShow:!0,zoomToExtent:!1,isFilter:!0})};
